from . import nivel
from . import curso
from . import paralelo
from . import materia
from . import asignatura
from . import horario
from . import asistencia
from . import detalle_asistencia
from . import actividad
from . import detalle_actividad
